language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly
        
branches:
  only:
    - master

before_install:
  - composer self-update

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/behat
